// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOLID.Database;

namespace SOLID.Database.Migrations
{
    [DbContext(typeof(DbContextSolid))]
    partial class DbContextSolidModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SOLID.Models.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountType");

                    b.Property<double>("Balance");

                    b.HasKey("ID");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<int>("AccountType");
                });

            modelBuilder.Entity("SOLID.Models.Models.CheckingAccount", b =>
                {
                    b.HasBaseType("SOLID.Models.Models.Account");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SOLID.Models.Models.SavingsAccount", b =>
                {
                    b.HasBaseType("SOLID.Models.Models.Account");

                    b.HasDiscriminator().HasValue(2);
                });
#pragma warning restore 612, 618
        }
    }
}
